- type: entity
  parent: ProtolatheMachineCircuitboard
  id: ProtolatheAncientMachineCircuitboard

- type: entity
  parent: CircuitImprinterMachineCircuitboard
  id: CircuitImprinterAncientMachineCircuitboard
