using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Recruitment;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Orion.Recruitment.UI;

[GenerateTypedNameReferences]
public sealed partial class RecruitmentMemberListWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public RecruitmentMemberListWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(RecruitmentMemberListBuiState state)
    {
        var localizedOrgName = Loc.GetString(state.OrganizationName);
        OrganizationLabel.Text = Loc.GetString("recruitment-member-list-organization",
            ("organization", localizedOrgName));
        MemberCountLabel.Text = Loc.GetString("recruitment-member-list-count",
            ("count", state.Members.Length));

        MembersContainer.RemoveAllChildren();

        if (state.Members.Length == 0)
        {
            NoMembersLabel.Visible = true;
            MemberScroller.Visible = false;
            return;
        }

        NoMembersLabel.Visible = false;
        MemberScroller.Visible = true;

        var headerRow = CreateHeaderRow();
        MembersContainer.AddChild(headerRow);

        var divider = new PanelContainer { StyleClasses = { "LowDivider" } };
        MembersContainer.AddChild(divider);

        // Create member rows
        foreach (var member in state.Members)
        {
            var memberRow = CreateMemberRow(member);
            MembersContainer.AddChild(memberRow);
        }
    }

    private static BoxContainer CreateHeaderRow()
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(5),
        };

        row.AddChild(new Label
        {
            Text = Loc.GetString("recruitment-member-list-header-name"),
            MinWidth = 150,
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        });

        row.AddChild(new Control { MinSize = new Vector2(5, 0) });

        row.AddChild(new Label
        {
            Text = Loc.GetString("recruitment-member-list-header-recruiter"),
            MinWidth = 150,
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        });

        row.AddChild(new Control { MinSize = new Vector2(5, 0) });

        row.AddChild(new Label
        {
            Text = Loc.GetString("recruitment-member-list-header-time"),
            MinWidth = 150,
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        });

        return row;
    }

    private BoxContainer CreateMemberRow(RecruitmentMemberListBuiState.RecruitedMemberData member)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(5, 2),
        };

        row.AddChild(new Label
        {
            Text = member.Name,
            MinWidth = 200,
        });

        row.AddChild(new Label
        {
            Text = member.RecruitedBy,
            MinWidth = 150,
        });

        var timeSince = _timing.CurTime - member.RecruitedAt;
        if (timeSince < TimeSpan.Zero)
            timeSince = TimeSpan.Zero;
        var timeText = FormatTimeSpan(timeSince);

        row.AddChild(new Label
        {
            Text = timeText,
            MinWidth = 150,
            HorizontalExpand = true,
        });

        return row;
    }

    private static string FormatTimeSpan(TimeSpan span)
    {
        var minutes = (int)span.TotalMinutes;
        var seconds = span.Seconds;

        return Loc.GetString("recruitment-member-list-time",
            ("minutes", minutes),
            ("seconds", seconds));
    }
}
