using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Recruitment;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Orion.Recruitment.UI;

[GenerateTypedNameReferences]
public sealed partial class RecruitmentMemberListWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public RecruitmentMemberListWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(RecruitmentMemberListBuiState state)
    {
        var localizedOrgName = Loc.GetString(state.OrganizationName);
        OrganizationLabel.Text = Loc.GetString("recruitment-member-list-organization",
            ("organization", localizedOrgName));
        MemberCountLabel.Text = Loc.GetString("recruitment-member-list-count",
            ("count", state.Members.Length));

        NameColumn.RemoveAllChildren();
        RecruiterColumn.RemoveAllChildren();
        TimeColumn.RemoveAllChildren();

        if (state.Members.Length == 0)
        {
            NoMembersLabel.Visible = true;
            MemberScroller.Visible = false;
            return;
        }

        NoMembersLabel.Visible = false;
        MemberScroller.Visible = true;

        AddColumnHeader(NameColumn, "recruitment-member-list-header-name");
        AddColumnHeader(RecruiterColumn, "recruitment-member-list-header-recruiter");
        AddColumnHeader(TimeColumn, "recruitment-member-list-header-time");

        AddDivider(NameColumn);
        AddDivider(RecruiterColumn);
        AddDivider(TimeColumn);

        foreach (var member in state.Members)
        {
            AddColumnValue(NameColumn, member.Name);
            AddColumnValue(RecruiterColumn, member.RecruitedBy);

            var timeSince = _timing.CurTime - member.RecruitedAt;
            if (timeSince < TimeSpan.Zero)
                timeSince = TimeSpan.Zero;
            var timeText = FormatTimeSpan(timeSince);
            AddColumnValue(TimeColumn, timeText);
        }
    }

    private static void AddColumnHeader(BoxContainer column, string locKey)
    {
        var header = new Label
        {
            Text = Loc.GetString(locKey),
            StyleClasses = { "LabelHeading" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(2, 5, 2, 5),
        };

        column.AddChild(header);
    }

    private static void AddDivider(BoxContainer column)
    {
        var divider = new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            MinSize = new System.Numerics.Vector2(0, 2),
            Margin = new Thickness(0, 2),
        };

        column.AddChild(divider);
    }

    private static void AddColumnValue(BoxContainer column, string text)
    {
        var label = new Label
        {
            Text = text,
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(5, 3),
            ClipText = true
        };
        column.AddChild(label);
    }

    private static string FormatTimeSpan(TimeSpan span)
    {
        var minutes = (int)span.TotalMinutes;
        var seconds = span.Seconds;

        return Loc.GetString("recruitment-member-list-time",
            ("minutes", minutes),
            ("seconds", seconds));
    }
}
