using Content.Shared._Orion.Bitrunning;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Bitrunning.UI.Netpod;

[GenerateTypedNameReferences]
public sealed partial class NetpodWindow : DefaultWindow
{
    public Action<string>? OnSelectOutfit;

    private NetpodBoundUiState? _state;

    public NetpodWindow()
    {
        RobustXamlLoader.Load(this);
        Search.OnTextChanged += _ => Rebuild();
        OutfitList.OnItemSelected += OnItemSelected;
    }

    public void UpdateState(NetpodBoundUiState state)
    {
        _state = state;
        Rebuild();
    }

    private void Rebuild()
    {
        OutfitList.Clear();
        if (_state == null)
            return;

        var filter = Search.Text.Trim().ToString();
        for (var i = 0; i < _state.Outfits.Count; i++)
        {
            var outfit = _state.Outfits[i];
            if (!string.IsNullOrEmpty(filter) &&
                outfit.Name.IndexOf(filter, StringComparison.OrdinalIgnoreCase) < 0 &&
                outfit.Id.IndexOf(filter, StringComparison.OrdinalIgnoreCase) < 0)
                continue;

            var item = new ItemList.Item(OutfitList)
            {
                Text = outfit.Name,
                Metadata = outfit.Id,
            };

            OutfitList.Add(item);

            if (_state.SelectedOutfit == outfit.Id)
                OutfitList[OutfitList.Count - 1].Selected = true;
        }
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemList[args.ItemIndex].Metadata is not string id)
            return;

        OnSelectOutfit?.Invoke(id);
    }
}
