using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyCardWindow : DefaultWindow
{
    public EconomyCardWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
