- type: startingGear
  id: ERTLeaderRedAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam
    head: ClothingHeadHelmetERTLeader
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol
    pocket2: FlashlightSeclite
  storage:
    back:
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon

- type: startingGear
  id: ERTJanitorRedAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTEngineerRedAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam
    head: ClothingHeadHelmetERTEngineer
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTSecurityRedAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam
    head: ClothingHeadHelmetERTSecurity
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponRevolverDeckard
    pocket2: FlashlightSeclite
  storage:
    back:
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
    - SpeedLoaderMagnum
    - SpeedLoaderMagnum

- type: startingGear
  id: ERTMedicalRedAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam
    head: ClothingHeadHelmetERTMedic
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: WeaponPistolMk58
    pocket2: Flare
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - JugOxandrolone
    - JugSalicylicAcid
    - ParamedHypo
    - CartridgeAtropine
    - CartridgeAtropine
    - MedicalBeamGunBattery
    - MagazinePistol
    - MagazinePistol
