- type: startingGear
  id: ERTLeaderGreenAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetERTLeader
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket2: FlashlightSeclite
  storage:
    back:
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed

- type: startingGear
  id: ERTJanitorGreenAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmorBasic
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTEngineerGreenAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMag
    head: ClothingHeadHelmetERTEngineer
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTSecurityGreenAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetERTSecurity
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket2: FlashlightSeclite
  storage:
    back:
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon

- type: startingGear
  id: ERTMedicalGreenAlertGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetERTMedic
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmorBasic
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: Flare
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - JugOxandrolone
    - JugSalicylicAcid
    - ParamedHypo
    - CartridgeAtropine
    - CartridgeAtropine
