- type: technology
  id: BasicArms
  name: research-technology-basic-arms-name
  description: research-technology-basic-arms-desc
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: beanbag
  discipline: Arsenal
  tier: 1
  startingTechnology: true
  cost: 500
  recipeUnlocks:
  - MagazineShotgunBeanbag
  - BoxBeanbag
  - MagazineBoxShotgunBeanbagHighCaliber 
  - ModularReceiver
  position: 0,0

- type: technology
  id: SecurityEquipment
  name: research-technology-security-equipment-name
  description: research-technology-security-equipment-desc
  icon:
    sprite: Objects/Tools/seclite.rsi
    state: seclite
  discipline: Arsenal
  tier: 1
  announceChannels:
  - Security
  cost: 2500
  technologyPrerequisites:
  - BasicArms
  recipeUnlocks:
  - SurveillanceWirelessCameraBodySecurity
  - ContrabandDetectorCircuitboard
  - PepperSpray
  - Zipties
  - FlashlightSeclite
  - ClothingBackpackElectropack
  position: -1,1

- type: technology
  id: CombatHUD
  name: research-technology-combat-hud-name
  description: research-technology-combat-hud-desc
  icon:
    sprite: Objects/Tools/seclite.rsi
    state: seclite
  discipline: Arsenal
  tier: 4
  announceChannels:
  - Security
  cost: 17500
  technologyPrerequisites:
  - BeamWeapons
  - AnomalyShells
  - NightVision
  recipeUnlocks:
  - ClothingEyesThermalVisionGoggles
  position: -2,1

- type: technology
  id: RiotSuppression
  name: research-technology-riot-suppression-name
  description: research-technology-riot-suppression-desc
  icon:
    sprite: _Goobstation/Objects/Weapons/Throwable/energy_bola.rsi
    state: icon
  discipline: Arsenal
  tier: 2
  announceChannels:
  - Security
  cost: 5000
  technologyPrerequisites:
  - SecurityEquipment
  recipeUnlocks:
  - TelescopicShield
  - RiotBulletShield
  - Handcuffs
  - BolaEnergy
  - Truncheon
  position: 1,1

- type: technology
  id: Explosives
  name: research-technology-explosives-name
  description: research-technology-explosives-desc
  icon:
    sprite: Objects/Weapons/Grenades/smoke.rsi
    state: icon
  discipline: Arsenal
  tier: 3
  announceChannels:
  - Security
  - Medical
  cost: 7500
  technologyPrerequisites:
  - RiotSuppression
  requiredExperiments:
  - OrdnanceExplosiveLowyieldbomb
  recipeUnlocks:
  - ModularGrenade
  - SmokeGrenade
  - FlashPayload
  - ChemicalPayload
  - ShrapnelPayload
  position: 1,0

- type: technology
  id: ExoticAmmo
  name: research-technology-exotic-ammo-name
  description: research-technology-exotic-ammo-desc
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: base
  discipline: Arsenal
  tier: 4
  announceChannels:
  - Security
  cost: 10000
  technologyPrerequisites:
  - Explosives
  discountExperiments:
  - OrdnanceExplosiveHighyieldbomb
  discountExperimentCosts:
    OrdnanceExplosiveHighyieldbomb: 10000
  recipeUnlocks:
  # Incendiary
  - BoxShotgunIncendiary
  - MagazineRifleIncendiary
  - MagazinePistolIncendiary
  - MagazinePistolSubMachineGunIncendiary
  - MagazineBoxShotgunIncendiaryHighCaliber
  - SpeedLoaderMagnumIncendiary
  - MagazineShotgunIncendiary
  - MagazineBoxPistolIncendiary
  - MagazineBoxMagnumIncendiary
  - MagazineBoxRifle762Incendiary
  - MagazineRifle762Incendiary
  - MagazineBoxRifleIncendiary
  # Uranium
  - MagazineRifleUranium
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunUranium
  - SpeedLoaderMagnumUranium
  - MagazineBoxPistolUranium
  - MagazineBoxMagnumUranium
  - MagazineBoxRifle762Uranium
  - MagazineRifle762Uranium
  - MagazineBoxRifleUranium
  - BoxShotgunUranium
  - MagazineBoxShotgunUraniumHighCaliber
  # Tranquilizer
  - BoxShellTranquilizer
  # Shuttle
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty
  position: 2,-1

- type: technology
  id: ElectricWeapons
  name: research-technology-electric-weapons-name
  description: research-technology-electric-weapons-desc
  icon:
    sprite: _Goobstation/Objects/Weapons/Guns/Battery/ion_rifle.rsi
    state: base
  discipline: Arsenal
  tier: 3
  announceChannels:
  - Security
  cost: 7500
  technologyPrerequisites:
  - RiotSuppression
  recipeUnlocks:
  - WeaponEnergyIonRifle
  - PowerCellIonRevolver
  - WeaponTemperatureGun
  position: 3,1

- type: technology
  id: BeamWeapons
  name: research-technology-beam-weapons-name
  description: research-technology-beam-weapons-desc
  icon:
    sprite: Objects/Weapons/Guns/Battery/xray.rsi
    state: icon
  discipline: Arsenal
  tier: 4
  announceChannels:
  - Security
  cost: 10000
  technologyPrerequisites:
  - ElectricWeapons
  recipeUnlocks:
  - WeaponXrayCannon
  - HoloprojectorSecurityAdvanced
  - PowerCellXrayRevolver
  - PowerCellXraySMG
  - PowerCellXraySniper
  - AntiMindControlDevice
  position: 4,1

- type: technology
  id: WeaponizedLaserManipulation
  name: research-technology-weaponized-laser-manipulation
  icon:
    sprite: Objects/Weapons/Guns/Battery/laser_gun.rsi
    state: icon
  discipline: Arsenal
  tier: 1
  announceChannels:
  - Security
  cost: 7500
  technologyPrerequisites:
  - ExoticAmmo
  recipeUnlocks:
  - WeaponLaserCarbine
  - WeaponLaserCannon
  position: 4,2

- type: technology
  id: PortableMicrofusionWeaponry
  name: research-technology-portable-microfusion-weaponry
  icon:
    sprite: Objects/Weapons/Guns/Battery/advancedlasergun.rsi
    state: icon
  discipline: Arsenal
  tier: 3
  announceChannels:
  - Security
  cost: 20000
  technologyPrerequisites:
  - BeamWeapons
  - WeaponizedLaserManipulation
  - PartsBluespace
  recipeUnlocks:
  - WeaponAdvancedLaser
  - PortableRecharger
  - EnergyMagRifleOverchargeLethal
  - PowerCellOverchargedRevolver
  - PowerCellOverchargedSMG
  - PowerCellOverchargedSniper
  position: 4,3
