// SPDX-FileCopyrightText: 2023 Checkraze <71046427+Cheackraze@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo.BUI;
using Content.Shared.Materials;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoPalletMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!; // Orion

    public Action? SellRequested;
    public Action? AppraiseRequested;

    public CargoPalletMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Orion

        // Orion-Start
        TabContainer.SetTabTitle(0, Loc.GetString("cargo-pallet-tab-sales"));
        TabContainer.SetTabTitle(1, Loc.GetString("cargo-pallet-tab-analytics"));
        // Orion-End

        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
    }

    // Orion-Start
    public void UpdateState(CargoPalletConsoleInterfaceState state)
    {
        SetEnabled(state.Enabled);
        SetAppraisal(state.Appraisal);
        SetCount(state.Count);
        BuildMarketAnalytics(state);
    }

    private void BuildMarketAnalytics(CargoPalletConsoleInterfaceState state)
    {
        IncreasedContainer.RemoveAllChildren();
        DecreasedContainer.RemoveAllChildren();
        RecentContainer.RemoveAllChildren();

        var increased = state.ActiveChanges.Where(c => c.Multiplier > 1f).OrderByDescending(c => c.Multiplier).ToList();
        var decreased = state.ActiveChanges.Where(c => c.Multiplier < 1f).OrderBy(c => c.Multiplier).ToList();

        foreach (var change in increased)
        {
            IncreasedContainer.AddChild(BuildChangeLabel(change));
        }

        foreach (var change in decreased)
        {
            DecreasedContainer.AddChild(BuildChangeLabel(change));
        }

        foreach (var change in state.RecentChanges.OrderByDescending(c => c.Sequence).Take(12))
        {
            RecentContainer.AddChild(BuildChangeLabel(change, true));
        }

        NoChangesLabel.Visible = state.ActiveChanges.Count == 0;
    }

    private Control BuildChangeLabel(CargoPalletMarketChangeData change, bool withSequence = false)
    {
        var materialName = change.MaterialProto;
        if (_prototype.TryIndex<MaterialPrototype>(change.MaterialProto, out var material) && !string.IsNullOrWhiteSpace(material.Name))
            materialName = Loc.GetString(material.Name);

        var direction = change.Multiplier >= 1f
            ? Loc.GetString("cargo-pallet-market-direction-up")
            : Loc.GetString("cargo-pallet-market-direction-down");

        var percent = (change.Multiplier - 1f) * 100f;
        var sequence = withSequence && change.Sequence > 0
            ? Loc.GetString("cargo-pallet-market-sequence", ("sequence", change.Sequence))
            : string.Empty;

        return new Label
        {
            Text = Loc.GetString("cargo-pallet-market-change-row",
                ("material", materialName),
                ("direction", direction),
                ("percent", MathF.Round(percent, 1)),
                ("multiplier", MathF.Round(change.Multiplier, 2)),
                ("sequence", sequence)),
        };
    }
    // Orion-End

    public void SetAppraisal(int amount)
    {
        AppraisalLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", amount.ToString()));
    }

    public void SetCount(int count)
    {
        CountLabel.Text = count.ToString();
    }

    public void SetEnabled(bool enabled)
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs obj)
    {
        AppraiseRequested?.Invoke();
    }
}
