using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class FundingAllocationMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly EntityQuery<StationBankAccountComponent> _bankQuery;

    public event Action<Dictionary<ProtoId<CargoAccountPrototype>, int>, double, double>? OnSavePressed;

    private EntityUid? _station;
    private bool _allowPrimaryAccountAllocation;
    private bool _allowPrimaryCutAdjustment;
    private bool _lockboxCutEnabled;

    private double _primaryCut;
    private double _lockboxCut;

//    private readonly HashSet<Control> _addedControls = new(); // Orion-Edit
    // Orion-Start
    private readonly HashSet<Control> _distributionControls = new();
    private readonly HashSet<Control> _economyAccountControls = new();

    private readonly HashSet<Control> _transactionControls = new();

    // Orion-End
    private readonly List<SpinBox> _spinBoxes = new();
    private readonly Dictionary<ProtoId<CargoAccountPrototype>, RichTextLabel> _balanceLabels = new();

    public FundingAllocationMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bankQuery = _entityManager.GetEntityQuery<StationBankAccountComponent>();

        // Orion-Start
        TabContainer.SetTabTitle(0, Loc.GetString("cargo-funding-alloc-console-tab-distribution"));
        TabContainer.SetTabTitle(1, Loc.GetString("cargo-funding-alloc-console-tab-economy"));
        // Orion-End

        PrimaryCut.ValueChanged += args =>
        {
            _primaryCut = args.Value / 100.0; // Orion-Edit
            UpdateButtonDisabled();
        };

        LockboxCut.ValueChanged += args =>
        {
            _lockboxCut = 1.0 - args.Value / 100.0; // Orion-Edit
            UpdateButtonDisabled();
        };

        SaveButton.OnPressed += _ =>
        {
            if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
                return;

            // Orion-Edit-Start
            var accounts = EditableAccounts(bank)
                .OrderBy(p => p.Key)
                .Select(p => p.Key)
                .ToList();

            var editedPercents = new Dictionary<ProtoId<CargoAccountPrototype>, int>();
            for (var i = 0; i < accounts.Count; i++)
            {
                editedPercents.Add(accounts[i], _spinBoxes[i].Value);
            }

            OnSavePressed?.Invoke(editedPercents, _primaryCut, _lockboxCut);
            // Orion-Edit-End
            SaveButton.Disabled = true;
        };

        // Orion-Edit-Start
        _cfg.OnValueChanged(CCVars.AllowPrimaryAccountAllocation,
            enabled => _allowPrimaryAccountAllocation = enabled,
            true);
        _cfg.OnValueChanged(CCVars.AllowPrimaryCutAdjustment, enabled => _allowPrimaryCutAdjustment = enabled, true);
        _cfg.OnValueChanged(CCVars.LockboxCutEnabled, enabled => _lockboxCutEnabled = enabled, true);
        // Orion-Edit-End

        BuildEntries();
    }

    private IEnumerable<KeyValuePair<ProtoId<CargoAccountPrototype>, int>> EditableAccounts(StationBankAccountComponent bank)
    {
        foreach (var kvp in bank.Accounts)
        {
            if (_allowPrimaryAccountAllocation || kvp.Key != bank.PrimaryAccount)
                yield return kvp;
        }
    }

    // Orion-Start
    private void BuildEconomy(FundingAllocationConsoleBuiState state)
    {
        foreach (var control in _economyAccountControls)
        {
            control.Orphan();
        }

        foreach (var control in _transactionControls)
        {
            control.Orphan();
        }

        _economyAccountControls.Clear();
        _transactionControls.Clear();

        var accountsByEntity = state.EconomyAccounts.ToDictionary(a => a.Account);

        NoAccountsLabel.Visible = state.EconomyAccounts.Count == 0;
        foreach (var account in state.EconomyAccounts.OrderBy(a => a.AccountId))
        {
            var code = new RichTextLabel
            {
                Text = $"[font=\"Monospace\"]{MaskAccountCode(account.AccountId)}[/font]",
                HorizontalAlignment = HAlignment.Center,
            };

            var name = new RichTextLabel
            {
                Text = account.AccountName,
                HorizontalAlignment = HAlignment.Center,
            };

            var roleText = account.DepartmentId is { } dep &&
                           _prototypeManager.TryIndex<CargoAccountPrototype>(dep, out var proto)
                ? Loc.GetString(proto.Name)
                : Loc.GetString("cargo-funding-alloc-console-economy-role-none");

            var role = new RichTextLabel
            {
                Text = roleText,
                HorizontalAlignment = HAlignment.Center,
            };

            var balance = new RichTextLabel
            {
                Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", account.Balance)),
                HorizontalAlignment = HAlignment.Center,
            };

            EconomyAccountsContainer.AddChild(code);
            EconomyAccountsContainer.AddChild(name);
            EconomyAccountsContainer.AddChild(role);
            EconomyAccountsContainer.AddChild(balance);

            _economyAccountControls.UnionWith(new Control[] { code, name, role, balance });
        }

        NoTransactionsLabel.Visible = state.Transactions.Count == 0;
        foreach (var transaction in state.Transactions.OrderByDescending(t => t.Time).ThenByDescending(t => t.Index))
        {
            accountsByEntity.TryGetValue(transaction.Account, out var mainAccount);
            accountsByEntity.TryGetValue(transaction.Counterparty ?? default, out var counterpartyAccount);

            var incoming = transaction.Delta > 0;
            var operationType = incoming
                ? Loc.GetString("cargo-funding-alloc-console-economy-operation-income")
                : Loc.GetString("cargo-funding-alloc-console-economy-operation-expense");

            var unknownText = Loc.GetString("cargo-funding-alloc-console-economy-unknown");
            var from = incoming
                ? counterpartyAccount?.AccountName ?? unknownText
                : mainAccount?.AccountName ?? unknownText;
            var to = incoming
                ? mainAccount?.AccountName ?? unknownText
                : counterpartyAccount?.AccountName ?? unknownText;

            var controls = new Control[]
            {
                new RichTextLabel { Text = operationType, HorizontalAlignment = HAlignment.Center },
                new RichTextLabel
                {
                    Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", transaction.Delta)),
                    HorizontalAlignment = HAlignment.Center,
                },
                new RichTextLabel { Text = from, HorizontalAlignment = HAlignment.Center },
                new RichTextLabel { Text = to, HorizontalAlignment = HAlignment.Center },
                new RichTextLabel { Text = LocalizeReason(transaction.Reason, transaction.ReasonData), HorizontalAlignment = HAlignment.Center },
                new RichTextLabel { Text = transaction.Time.ToString(@"hh\:mm\:ss"), HorizontalAlignment = HAlignment.Center },
            };

            foreach (var control in controls)
            {
                TransactionsContainer.AddChild(control);
                _transactionControls.Add(control);
            }
        }
    }

    private static string MaskAccountCode(string accountId)
    {
        return accountId.Length <= 4
            ? "####"
            : $"######{accountId[^4..]}";
    }

    private static string LocalizeReason(string reason, string? reasonData)
    {
        return reason switch
        {
            "card_deposit" => Loc.GetString("cargo-funding-alloc-console-reason-card-deposit"),
            "card_withdrawal" => Loc.GetString("cargo-funding-alloc-console-reason-card-withdrawal"),
            "payroll" => Loc.GetString("cargo-funding-alloc-console-reason-payroll", ("job", Loc.GetString($"job-name-{reasonData}"))),
            _ => Loc.GetString("cargo-funding-alloc-console-reason-generic", ("reason", reason)),
        };
    }
    // Orion-End

    // Orion-Edit-Start
    private void BuildEntries()
    {
        if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return;

        HelpLabel.Text = _allowPrimaryCutAdjustment
            ? Loc.GetString("cargo-funding-alloc-console-label-help-adjustible")
            : Loc.GetString("cargo-funding-alloc-console-label-help-non-adjustible",
                ("percent", (int) (bank.PrimaryCut * 100)));

        foreach (var control in _distributionControls)
        {
            control.Orphan();
        }

        _distributionControls.Clear();
        _spinBoxes.Clear();
        _balanceLabels.Clear();

        _primaryCut = bank.PrimaryCut;
        _lockboxCut = bank.LockboxCut;

        LockboxCut.OverrideValue(100 - (int) (_lockboxCut * 100));
        PrimaryCut.OverrideValue((int) (_primaryCut * 100));

        LockboxCut.IsValid = val => val is >= 0 and <= 100;
        PrimaryCut.IsValid = val => val is >= 0 and <= 100;

        LockboxCut.Visible = _lockboxCutEnabled;
        LockboxCutLabel.Visible = _lockboxCutEnabled;
        PrimaryCut.Visible = _allowPrimaryCutAdjustment;
        PrimaryCutLabel.Visible = _allowPrimaryCutAdjustment;

        var accounts = EditableAccounts(bank).OrderBy(p => p.Key);
        foreach (var (account, balance) in accounts)
        {
            var proto = _prototypeManager.Index(account);

            var accountName = new RichTextLabel
            {
                Modulate = proto.Color,
                Margin = new Thickness(0, 0, 10, 0),
            };

            accountName.SetMarkup($"[bold]{Loc.GetString(proto.Name)}[/bold]");

            var code = new RichTextLabel
            {
                Text = $"[font=\"Monospace\"]{Loc.GetString(proto.Code)}[/font]",
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5, 0),
            };

            var balanceLabel = new RichTextLabel
            {
                Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", balance)),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5, 0),
            };

            var cutSpinBox = new SpinBox
            {
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Value = (int) (bank.RevenueDistribution[account] * 100),
                IsValid = val => val is >= 0 and <= 100,
            };

            cutSpinBox.ValueChanged += _ => UpdateButtonDisabled();

            EntriesContainer.AddChild(accountName);
            EntriesContainer.AddChild(code);
            EntriesContainer.AddChild(balanceLabel);
            EntriesContainer.AddChild(cutSpinBox);

            _spinBoxes.Add(cutSpinBox);
            _balanceLabels.Add(account, balanceLabel);
            _distributionControls.UnionWith([accountName, code, balanceLabel, cutSpinBox]);
        }
    }
    // Orion-Edit-End

    // Orion-Edit-Start
    private void UpdateButtonDisabled()
    {
        if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return;

        var sum = _spinBoxes.Sum(s => s.Value);
        var incorrectSum = sum != 100;

        var differs = false;
        var accounts = EditableAccounts(bank)
            .OrderBy(p => p.Key)
            .Select(p => p.Key)
            .ToList();

        for (var i = 0; i < accounts.Count; i++)
        {
            var currentPercent = _spinBoxes[i].Value;
            var expectedPercent = (int) Math.Round(bank.RevenueDistribution[accounts[i]] * 100);

            if (currentPercent == expectedPercent)
                continue;

            differs = true;
            break;
        }

        differs = differs || _primaryCut != bank.PrimaryCut || _lockboxCut != bank.LockboxCut;

        SaveButton.Disabled = !differs || incorrectSum;

        var diff = sum - 100;
        SaveAlertLabel.Visible = incorrectSum;
        SaveAlertLabel.SetMarkup(Loc.GetString(
            "cargo-funding-alloc-console-label-save-fail",
            ("pos", Math.Sign(diff)),
            ("val", Math.Abs(diff))));
    }
    // Orion-Edit-End

    public void Update(FundingAllocationConsoleBuiState state)
    {
        _station = _entityManager.GetEntity(state.Station);

        BuildEntries();
        BuildEconomy(state); // Orion
        UpdateButtonDisabled();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_bankQuery.TryComp(_station, out var bank))
            return;

        foreach (var (account, label) in _balanceLabels)
        {
            label.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", bank.Accounts[account]));
        }
    }
}
