using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DestructiveAnalyzerMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public event Action? OnServerButtonPressed;
    public event Action<string>? OnMethodSelected;
    public event Action? OnAnalyzePressed;
    public event Action? OnEjectPressed;

    public DestructiveAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        AnalyzeButton.OnPressed += _ => OnAnalyzePressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        MethodOption.OnItemSelected += args =>
        {
            if (MethodOption.GetItemMetadata(args.Id) is not string id)
                return;

            OnMethodSelected?.Invoke(id);
        };
    }

    private static string LocalizeMethod(string methodId)
    {
        var key = $"research-machine-destructive-method-{methodId.ToLowerInvariant()}";
        return Loc.TryGetString(key, out var localized) ? localized : methodId;
    }

    public void UpdateState(DestructiveAnalyzerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ConnectedServerName));

        InsertedItemLabel.Text = Loc.GetString("research-machine-common-last-subject") + ": " + (state.InsertedItem ?? Loc.GetString("research-machine-common-none"));
        if (state.InsertedItemEntity is { } net && _entManager.TryGetEntity(net, out var uid))
            InsertedItemSprite.SetEntity(uid);
        else
            InsertedItemSprite.SetEntity(null);

        MethodOption.Clear();

        MethodContainer.Visible = state.Methods.Count > 0;
        MethodOption.Visible = state.Methods.Count > 0;
        for (var i = 0; i < state.Methods.Count; i++)
        {
            var method = state.Methods[i];
            MethodOption.AddItem(LocalizeMethod(method), i);
            MethodOption.SetItemMetadata(i, method);
            if (method == state.SelectedMethod)
                MethodOption.SelectId(i);
        }

        var lastOperation = new FormattedMessage();
        lastOperation.AddText($"{Loc.GetString("research-machine-common-last-subject")}: {(string.IsNullOrWhiteSpace(state.LastSubject)
            ? Loc.GetString("research-machine-common-none")
            : state.LastSubject)}\n");
        lastOperation.AddText($"{Loc.GetString("research-machine-common-last-result")}: {(string.IsNullOrWhiteSpace(state.LastResult)
            ? Loc.GetString("research-machine-common-none")
            : state.LastResult)}");
        LastOperationLabel.SetMessage(lastOperation);

        EjectButton.Disabled = state.InsertedItem == null;
    }
}
