using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DestructiveAnalyzerMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;

    public DestructiveAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
    }

    public void UpdateState(DestructiveAnalyzerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ConnectedServerName));

        var balances = new FormattedMessage();
        balances.AddMarkupOrThrow($"[color=lightblue]{Loc.GetString("research-machine-common-balances-title")}[/color]");
        foreach (var point in state.PointBalances)
        {
            balances.PushNewline();
            balances.AddMarkupOrThrow($"• [color=lightgreen]{point.Type}[/color]: {point.Amount}");
        }
        if (state.PointBalances.Count == 0)
        {
            balances.PushNewline();
            balances.AddMarkupOrThrow($"[color=gray]{Loc.GetString("research-machine-common-balances-empty")}[/color]");
        }

        BalanceLabel.SetMessage(balances);

        var requirements = new FormattedMessage();
        requirements.AddMarkupOrThrow(Loc.GetString("research-machine-destructive-requirements-line-1"));
        requirements.PushNewline();
        requirements.AddMarkupOrThrow(Loc.GetString("research-machine-destructive-requirements-line-2"));
        RequirementsLabel.SetMessage(requirements);

        var lastOperation = new FormattedMessage();
        lastOperation.AddMarkupOrThrow($"{Loc.GetString("research-machine-common-last-subject")}: [color=lightblue]{(string.IsNullOrWhiteSpace(state.LastSubject) ? Loc.GetString("research-machine-common-none") : state.LastSubject)}[/color]");
        lastOperation.PushNewline();
        lastOperation.AddMarkupOrThrow($"{Loc.GetString("research-machine-common-last-result")}: [color=lightblue]{(string.IsNullOrWhiteSpace(state.LastResult) ? Loc.GetString("research-machine-common-none") : state.LastResult)}[/color]");
        LastOperationLabel.SetMessage(lastOperation);
    }
}
