using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Research;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ExperimentatorMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;

    public ExperimentatorMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
    }

    private static string FormatRewards(List<ResearchPointAmount> rewards)
    {
        return rewards.Count == 0
            ? Loc.GetString("research-machine-common-none")
            : string.Join(", ", rewards.Select(reward => $"{reward.Type}: {reward.Amount}"));
    }

    public void UpdateState(ExperimentatorBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ConnectedServerName));

        var balances = new FormattedMessage();
        balances.AddMarkupOrThrow($"[color=lightblue]{Loc.GetString("research-machine-common-balances-title")}[/color]");
        foreach (var point in state.PointBalances)
        {
            balances.PushNewline();
            balances.AddMarkupOrThrow($"• [color=lightgreen]{point.Type}[/color]: {point.Amount}");
        }
        if (state.PointBalances.Count == 0)
        {
            balances.PushNewline();
            balances.AddMarkupOrThrow($"[color=gray]{Loc.GetString("research-machine-common-balances-empty")}[/color]");
        }

        BalanceLabel.SetMessage(balances);

        var operationsMessage = new FormattedMessage();
        if (state.Operations.Count == 0)
        {
            operationsMessage.AddMarkupOrThrow($"[color=gray]{Loc.GetString("research-machine-experimentator-operations-empty")}[/color]");
        }

        for (var index = 0; index < state.Operations.Count; index++)
        {
            var operation = state.Operations[index];
            if (index > 0)
                operationsMessage.PushNewline();

            operationsMessage.AddMarkupOrThrow($"[color=lightblue]{Loc.GetString("research-machine-experimentator-operation-label", ("index", index + 1))}[/color]");
            operationsMessage.PushNewline();
            operationsMessage.AddMarkupOrThrow($"{Loc.GetString("research-machine-experimentator-operation-tags")}: {string.Join(", ", operation.RequiredTags)}");
            operationsMessage.PushNewline();
            operationsMessage.AddMarkupOrThrow($"{Loc.GetString("research-machine-experimentator-operation-success")}: {(int) (operation.SuccessChance * 100)}%");
            operationsMessage.PushNewline();
            operationsMessage.AddMarkupOrThrow($"{Loc.GetString("research-machine-experimentator-operation-backfire")}: {(int) (operation.BackfireChance * 100)}%");
            operationsMessage.PushNewline();
            operationsMessage.AddMarkupOrThrow($"{Loc.GetString("research-machine-experimentator-operation-success-reward")}: {FormatRewards(operation.SuccessRewards)}");
            operationsMessage.PushNewline();
            operationsMessage.AddMarkupOrThrow($"{Loc.GetString("research-machine-experimentator-operation-failure-reward")}: {FormatRewards(operation.FailureRewards)}");
        }

        OperationsLabel.SetMessage(operationsMessage);

        var lastOperation = new FormattedMessage();
        lastOperation.AddMarkupOrThrow($"{Loc.GetString("research-machine-common-last-subject")}: [color=lightblue]{(string.IsNullOrWhiteSpace(state.LastSubject) ? Loc.GetString("research-machine-common-none") : state.LastSubject)}[/color]");
        lastOperation.PushNewline();
        lastOperation.AddMarkupOrThrow($"{Loc.GetString("research-machine-common-last-result")}: [color=lightblue]{(string.IsNullOrWhiteSpace(state.LastResult) ? Loc.GetString("research-machine-common-none") : state.LastResult)}[/color]");
        LastOperationLabel.SetMessage(lastOperation);
    }
}
