using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ExperimentatorMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action? OnPerformPressed;

    public ExperimentatorMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        PerformButton.OnPressed += _ => OnPerformPressed?.Invoke();
    }

    public void UpdateState(ExperimentatorBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", state.ConnectedServerName));

        InsertedItemLabel.Text = Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-experiment-scanner-status")),
            ("value", state.InsertedItem ?? Loc.GetString("research-machine-common-none")));

        var experiments = new FormattedMessage();
        foreach (var experiment in state.Experiments)
        {
            experiments.AddMarkupOrThrow($"[bold]{experiment.Name}[/bold]");
            experiments.PushNewline();
            experiments.AddText(experiment.Description);
            experiments.PushNewline();
            experiments.AddText(Loc.GetString("research-machine-experiment-progress",
                ("objective", experiment.Objective),
                ("progress", experiment.Progress),
                ("target", experiment.Target)));
            experiments.PushNewline();
            experiments.PushNewline();
        }

        if (state.Experiments.Count == 0)
            experiments.AddMarkupOrThrow($"[color=gray]{Loc.GetString("research-machine-experimentator-operations-empty")}[/color]");

        OperationsLabel.SetMessage(experiments);

        var result = string.IsNullOrWhiteSpace(state.LastResult)
            ? Loc.GetString("research-machine-common-none")
            : state.LastResult;

        var lastOperation = new FormattedMessage();
        lastOperation.AddText(Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-common-last-result")),
            ("value", result)));
        LastOperationLabel.SetMessage(lastOperation);
    }
}
