using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleLogWindow : FancyWindow
{
    public FancyResearchConsoleLogWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetJournalMessage(FormattedMessage message)
    {
        JournalLabel.SetMessage(message);
    }
}
