using System.Linq;
using System.Numerics;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerControlMenu : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    private readonly SpriteSystem _sprite;

    public event Action<int>? OnToggleRequested;

    public ResearchServerControlMenu()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
        _sprite = _entitySystemManager.GetEntitySystem<SpriteSystem>();
    }

    private string LocalizePointType(string type)
    {
        var key = $"research-point-type-{type.ToLowerInvariant()}";
        return _loc.TryGetString(key, out var localized) ? localized : type;
    }

    private static string FormatServerName(string name)
    {
        const string prefix = "RND-Server";
        if (!name.StartsWith(prefix))
            return name;

        var suffix = name[prefix.Length..].TrimStart();
        return string.IsNullOrWhiteSpace(suffix)
            ? Loc.GetString("research-server-name-base")
            : Loc.GetString("research-server-name-with-suffix", ("suffix", suffix));
    }

    public void Populate(List<ResearchServerControlEntry> servers)
    {
        ServerEntries.DisposeAllChildren();

        foreach (var server in servers)
        {
            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var generation = string.Join(", ", server.PointGeneration.Select(p => $"{LocalizePointType(p.Type)}: {p.Amount}/s"));
            var balances = string.Join(", ", server.Balances.Select(p => $"{LocalizePointType(p.Type)}: {p.Amount}"));

            var nameRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
            var icon = new TextureRect
            {
                TextureScale = new Vector2(1.5f, 1.5f),
                VerticalAlignment = VAlignment.Center,
                Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(new ResPath("/Textures/Structures/Machines/server.rsi"), "server")),
            };
            nameRow.AddChild(icon);
            nameRow.AddChild(new Label { Text = $"#{server.Id} {FormatServerName(server.Name)}" });
            line.AddChild(nameRow);

            line.AddChild(new Label { Text = Loc.GetString("research-server-control-generation", ("state", Loc.GetString(server.GenerationEnabled ? "research-server-control-state-enabled" : "research-server-control-state-disabled")), ("total", server.TotalPointsPerSecond)) });
            line.AddChild(new Label { Text = Loc.GetString("research-server-control-generation-by-type", ("generation", generation)) });
            line.AddChild(new Label { Text = Loc.GetString("research-server-control-balances", ("balances", balances)) });
            line.AddChild(new Label { Text = Loc.GetString("research-server-control-logs", ("count", server.LogCount)) });

            var toggle = new Button { Text = server.GenerationEnabled ? Loc.GetString("research-server-control-disable") : Loc.GetString("research-server-control-enable") };
            var id = server.Id;
            toggle.OnPressed += _ => OnToggleRequested?.Invoke(id);
            line.AddChild(toggle);

            ServerEntries.AddChild(line);
            ServerEntries.AddChild(new HSeparator());
        }
    }
}
