using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Orion.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerControlMenu : DefaultWindow
{
    public event Action<int>? OnToggleRequested;

    public ResearchServerControlMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<ResearchServerControlEntry> servers)
    {
        ServerEntries.DisposeAllChildren();

        foreach (var server in servers)
        {
            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var generation = string.Join(", ", server.PointGeneration.Select(p => $"{p.Type}: {p.Amount}/s"));
            var balances = string.Join(", ", server.Balances.Select(p => $"{p.Type}: {p.Amount}"));

            line.AddChild(new Label { Text = $"#{server.Id} {server.Name}" });
            line.AddChild(new Label { Text = $"Generation: {(server.GenerationEnabled ? "Enabled" : "Disabled")} | Total: {server.TotalPointsPerSecond}/s" });
            line.AddChild(new Label { Text = $"By Type: {generation}" });
            line.AddChild(new Label { Text = $"Balances: {balances}" });
            line.AddChild(new Label { Text = $"Logs: {server.LogCount}" });

            var toggle = new Button { Text = server.GenerationEnabled ? Loc.GetString("research-server-control-disable") : Loc.GetString("research-server-control-enable") };
            var id = server.Id;
            toggle.OnPressed += _ => OnToggleRequested?.Invoke(id);
            line.AddChild(toggle);

            ServerEntries.AddChild(line);
            ServerEntries.AddChild(new HSeparator());
        }
    }
}
