using Content.Client.Message;
using Content.Shared._Orion.Bitrunning;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Bitrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class QuantumConsoleWindow : DefaultWindow
{
    public Action<string>? OnLoadDomain;
    public Action? OnRandomDomain;
    public Action? OnStopDomain;
    public Action? OnRefresh;

    public QuantumConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        RandomButton.OnPressed += _ => OnRandomDomain?.Invoke();
        StopButton.OnPressed += _ => OnStopDomain?.Invoke();
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void UpdateState(QuantumConsoleBoundUiState state)
    {
        ConnectedValue.Text = state.Connected ? Loc.GetString("bitrunning-console-connected") : Loc.GetString("bitrunning-console-disconnected");
        CurrentDomainValue.Text = state.CurrentDomain ?? "-";
        OccupantsValue.Text = state.Occupants.ToString();
        PointsValue.Text = state.Points.ToString();
        ScannerValue.Text = state.ScannerTier.ToString();
        StateValue.Text = state.State.ToString();

        DomainList.RemoveAllChildren();
        foreach (var domain in state.Domains)
        {
            var button = new Button
            {
                Text = Loc.GetString("bitrunning-ui-domain-button", ("name", domain.Name), ("cost", domain.Cost))
            };
            button.OnPressed += _ => OnLoadDomain?.Invoke(domain.Id);
            DomainList.AddChild(button);

            var label = new RichTextLabel();
            label.SetMarkup(Loc.GetString("bitrunning-ui-domain-info",
                ("description", domain.Description),
                ("reward", domain.Reward),
                ("difficulty", domain.Difficulty)));
            DomainList.AddChild(label);
        }
    }
}
