using System.Globalization;
using System.Numerics;
using Content.Shared._Orion.Bitrunning;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Bitrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class QuantumConsoleWindow : DefaultWindow
{
    public Action<string>? OnLoadDomain;
    public Action<bool>? OnBroadcastToggle;
    public Action? OnRandomDomain;
    public Action? OnStopDomain;
    public Action? OnRefresh;

    private QuantumConsoleBoundUiState? _lastState;
    private string? _selectedDifficulty;
    private bool _updatingToggle;

    public QuantumConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ApplyStaticStyling();
        ConfigureDifficultyTabs();

        RandomButton.OnPressed += _ => OnRandomDomain?.Invoke();
        StopButton.OnPressed += _ => OnStopDomain?.Invoke();
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        BroadcastToggle.OnToggled += args =>
        {
            if (_updatingToggle)
                return;

            OnBroadcastToggle?.Invoke(args.Pressed);
        };
    }

    public void UpdateState(QuantumConsoleBoundUiState state)
    {
        _lastState = state;

        ConnectedValue.Text = state.Connected
            ? Loc.GetString("bitrunning-console-connected")
            : Loc.GetString("bitrunning-console-disconnected");
        ConnectedValue.FontColorOverride = state.Connected ? Color.SpringGreen : Color.IndianRed;

        PointsValue.Text = Loc.GetString("bitrunning-ui-points-badge", ("points", state.Points.ToString(CultureInfo.InvariantCulture)));
        ClientsHeader.Text = Loc.GetString("bitrunning-ui-clients-header-count", ("count", state.Occupants.ToString(CultureInfo.InvariantCulture)));
        ScannerValue.Text = Loc.GetString("bitrunning-ui-scanner-inline", ("scanner", state.ScannerTier.ToString(CultureInfo.InvariantCulture)));
        StateValue.Text = GetStateText(state);

        CurrentDomainValue.Text = state.CurrentDomain ?? Loc.GetString("bitrunning-ui-current-domain-none");
        CurrentDomainValue.FontColorOverride = state.CurrentDomain == null ? Color.Silver : Color.AliceBlue;

        _updatingToggle = true;
        BroadcastToggle.Pressed = state.Broadcast;
        _updatingToggle = false;

        StopButton.Disabled = state.State != BitrunningServerState.Running;

        UpdateCooldown(state);
        RebuildDomainList(state);
        RebuildClientList(state);
        UpdateDifficultySelectionVisuals();
    }

    private static string GetStateText(QuantumConsoleBoundUiState state)
    {
        var text = state.State switch
        {
            BitrunningServerState.Ready => Loc.GetString("bitrunning-ui-state-ready"),
            BitrunningServerState.Running => Loc.GetString("bitrunning-ui-state-running"),
            BitrunningServerState.CoolingDown => Loc.GetString("bitrunning-ui-state-cooling"),
            _ => state.State.ToString(),
        };

        if (state.State != BitrunningServerState.CoolingDown)
            return Loc.GetString("bitrunning-ui-server-state", ("state", text));

        var remaining = TimeSpan.FromSeconds(state.CooldownRemainingSeconds);
        var formatted = $"{remaining.Minutes:D2}:{remaining.Seconds:D2}";
        text = Loc.GetString("bitrunning-ui-state-cooling-time", ("time", formatted));

        return Loc.GetString("bitrunning-ui-server-state", ("state", text));
    }

    private void UpdateCooldown(QuantumConsoleBoundUiState state)
    {
        if (state.State != BitrunningServerState.CoolingDown || state.CooldownTotalSeconds <= 0)
        {
            CooldownLabel.Text = Loc.GetString("bitrunning-ui-cooldown-ready");
            CooldownBar.Value = 1f;
            CooldownBar.ModulateSelfOverride = Color.FromHex("#3fa34d");
            return;
        }

        var progress = 1f - Math.Clamp(state.CooldownRemainingSeconds / state.CooldownTotalSeconds, 0f, 1f);
        CooldownLabel.Text = Loc.GetString("bitrunning-ui-cooldown-active");
        CooldownBar.Value = progress;
        CooldownBar.ModulateSelfOverride = Color.FromHex("#d19b2a");
    }

    private void RebuildDomainList(QuantumConsoleBoundUiState state)
    {
        DomainList.RemoveAllChildren();

        foreach (var domain in state.Domains)
        {
            if (_selectedDifficulty != null && !domain.Difficulty.Equals(_selectedDifficulty, StringComparison.OrdinalIgnoreCase))
                continue;

            DomainList.AddChild(CreateDomainRow(domain, state));
        }
    }

    private void RebuildClientList(QuantumConsoleBoundUiState state)
    {
        ClientList.RemoveAllChildren();

        if (state.ConnectedAvatars.Count == 0)
        {
            ClientList.AddChild(new Label
            {
                Text = Loc.GetString("bitrunning-ui-no-clients"),
                FontColorOverride = Color.FromHex("#8d8d8d"),
            });
            return;
        }

        foreach (var client in state.ConnectedAvatars)
        {
            ClientList.AddChild(CreateClientRow(client));
        }
    }

    private Control CreateDomainRow(BitrunningDomainListing domain, QuantumConsoleBoundUiState state)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            MinSize = new Vector2(0f, 23f),
        };

        var canDeploy = state.State != BitrunningServerState.Running && state.Points >= domain.Cost;
        var isCurrent = state.CurrentDomain != null && state.CurrentDomain.Equals(domain.Id, StringComparison.OrdinalIgnoreCase);

        var domainButton = new Button
        {
            HorizontalExpand = true,
            Text = Loc.GetString("bitrunning-ui-domain-entry-tg", ("name", domain.Name)),
            TextAlign = Label.AlignMode.Left,
            MinSize = new Vector2(0f, 23f),
            ModulateSelfOverride = GetDifficultyColor(domain.Difficulty),
        };
        domainButton.OnPressed += _ => SelectedDomainInfo.Text = Loc.GetString("bitrunning-ui-domain-info",
            ("description", domain.Description));

        var deployText = isCurrent && state.State == BitrunningServerState.Running
            ? Loc.GetString("bitrunning-ui-button-deployed")
            : Loc.GetString("bitrunning-ui-button-deploy");

        var deployButton = new Button
        {
            Text = deployText,
            MinSize = new Vector2(90f, 23f),
            Disabled = !canDeploy,
            ToolTip = canDeploy ? null : Loc.GetString("bitrunning-ui-cannot-deploy"),
        };
        deployButton.OnPressed += _ => OnLoadDomain?.Invoke(domain.Id);

        row.AddChild(domainButton);
        row.AddChild(deployButton);

        return row;
    }

    private static Control CreateClientRow(BitrunningOccupantListing client)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 5,
            MinSize = new Vector2(0f, 22f),
        };

        row.AddChild(new Label
        {
            Text = client.Name,
            HorizontalExpand = true,
        });

        var icons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 3,
        };

        icons.AddChild(CreateIconBadge("•", "bitrunning-ui-client-icon-linked"));
        icons.AddChild(CreateIconBadge("◔", "bitrunning-ui-client-icon-signal"));
        icons.AddChild(CreateIconBadge("◕", "bitrunning-ui-client-icon-active"));

        if (client.NoHit)
            icons.AddChild(CreateIconBadge("✓", "bitrunning-ui-client-icon-nohit"));

        row.AddChild(icons);
        row.AddChild(CreatePercentBadge(client.NoHit
            ? Loc.GetString("bitrunning-ui-client-percent-perfect")
            : Loc.GetString("bitrunning-ui-client-percent-online")));

        return row;
    }

    private static Control CreateIconBadge(string icon, string tooltipKey)
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1f2537"),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 0,
                ContentMarginBottomOverride = 0,
            },
            ToolTip = Loc.GetString(tooltipKey),
        };

        panel.AddChild(new Label
        {
            Text = icon,
            FontColorOverride = Color.Silver,
        });

        return panel;
    }

    private static Control CreatePercentBadge(string text)
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#4e9b23"),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 1,
                ContentMarginBottomOverride = 1,
            },
            MinSize = new Vector2(78f, 0f),
        };

        panel.AddChild(new Label
        {
            Text = text,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.White,
        });

        return panel;
    }

    private void ConfigureDifficultyTabs()
    {
        DifficultyPeaceful.Text = Loc.GetString("bitrunning-ui-difficulty-peaceful");
        DifficultyEasy.Text = Loc.GetString("bitrunning-ui-difficulty-easy");
        DifficultyMedium.Text = Loc.GetString("bitrunning-ui-difficulty-medium");
        DifficultyHard.Text = Loc.GetString("bitrunning-ui-difficulty-hard-skull");

        ConfigureDifficultyButton(DifficultyPeaceful, "Peaceful", DifficultyColor.Peaceful);
        ConfigureDifficultyButton(DifficultyEasy, "Easy", DifficultyColor.Easy);
        ConfigureDifficultyButton(DifficultyMedium, "Medium", DifficultyColor.Medium);
        ConfigureDifficultyButton(DifficultyHard, "Hard", DifficultyColor.Hard);
    }

    private void ConfigureDifficultyButton(Button button, string difficulty, Color color)
    {
        button.ModulateSelfOverride = color;
        button.OnPressed += _ =>
        {
            _selectedDifficulty = _selectedDifficulty == difficulty ? null : difficulty;

            if (_lastState != null)
                RebuildDomainList(_lastState);

            UpdateDifficultySelectionVisuals();
        };
    }

    private void UpdateDifficultySelectionVisuals()
    {
        ApplyDifficultyState(DifficultyPeaceful, "Peaceful");
        ApplyDifficultyState(DifficultyEasy, "Easy");
        ApplyDifficultyState(DifficultyMedium, "Medium");
        ApplyDifficultyState(DifficultyHard, "Hard");
    }

    private void ApplyDifficultyState(Button button, string difficulty)
    {
        var baseText = difficulty switch
        {
            "Peaceful" => Loc.GetString("bitrunning-ui-difficulty-peaceful"),
            "Easy" => Loc.GetString("bitrunning-ui-difficulty-easy"),
            "Medium" => Loc.GetString("bitrunning-ui-difficulty-medium"),
            "Hard" => Loc.GetString("bitrunning-ui-difficulty-hard-skull"),
            _ => difficulty,
        };

        var selected = _selectedDifficulty != null && _selectedDifficulty.Equals(difficulty, StringComparison.OrdinalIgnoreCase);
        button.Text = selected
            ? Loc.GetString("bitrunning-ui-difficulty-selected", ("name", baseText))
            : baseText;
    }

    private void ApplyStaticStyling()
    {
        DomainsPanel.PanelOverride = CreatePanelStyle("#111318");
        ClientsPanel.PanelOverride = CreatePanelStyle("#111318");
        ActiveDomainPanel.PanelOverride = CreatePanelStyle("#111318");
        ActiveDomainBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#225b99"),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 2,
            ContentMarginBottomOverride = 2,
        };
        PointsBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1e243a"),
            ContentMarginLeftOverride = 2,
            ContentMarginRightOverride = 2,
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1,
        };
        PointsValue.FontColorOverride = Color.HotPink;
        VirtualDomainsHeader.FontColorOverride = Color.White;
        ClientsHeader.FontColorOverride = Color.White;
        SelectedDomainInfo.FontColorOverride = Color.Silver;
        MetaRow.Visible = true;
    }

    private static StyleBoxFlat CreatePanelStyle(string hex)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(hex),
            BorderColor = Color.FromHex("#2a2d36"),
            BorderThickness = new Thickness(1),
        };
    }

    private static Color GetDifficultyColor(string difficulty)
    {
        return difficulty.ToLowerInvariant() switch
        {
            "peaceful" => DifficultyColor.Peaceful,
            "easy" => DifficultyColor.Easy,
            "medium" => DifficultyColor.Medium,
            "hard" => DifficultyColor.Hard,
            _ => Color.FromHex("#B03030"),
        };
    }

    private static class DifficultyColor
    {
        public static readonly Color Peaceful = Color.FromHex("#2ca85e");
        public static readonly Color Easy = Color.FromHex("#d4b300");
        public static readonly Color Medium = Color.FromHex("#d78500");
        public static readonly Color Hard = Color.FromHex("#d12a2a");
    }
}
