// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <143940725+FaDeOkno@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 FaDeOkno <logkedr18@gmail.com>
// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 SX-7 <sn1.test.preria.2002@gmail.com>
// SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Goobstation.Common.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    // Public fields
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype, ResearchAvailability>? SelectAction;
    private ResearchAvailability _availability;

    // Some visuals
    private Color _color;
    private Color _borderColor;
    private Color _hoveredColor;

    public FancyResearchConsoleItem(TechnologyPrototype proto, SpriteSystem sprite, IPrototypeManager prototypeManager, ResearchAvailability availability)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _availability = availability;
        Prototype = proto;

        ResearchDisplay.Texture = sprite.Frame0(proto.Icon);

        if (prototypeManager.TryIndex(proto.Discipline, out var discipline))
        {
            DisciplineDisplay.Texture = sprite.Frame0(discipline.Icon);

            if (DisciplineBadge.PanelOverride is StyleBoxFlat badge)
                badge.BorderColor = discipline.Color;
        }

        Button.OnPressed += Selected;
        Button.OnDrawModeChanged += UpdateColor;

        (_color, _hoveredColor, _borderColor) = availability switch
        {
            ResearchAvailability.Researched => (Color.DarkOliveGreen, Color.PaleGreen, Color.LimeGreen),
            ResearchAvailability.Available => (Color.FromHex("#7c7d2a"), Color.FromHex("#ecfa52"), Color.FromHex("#e8fa25")),
            ResearchAvailability.PrereqsMet => (Color.FromHex("#6b572f"), Color.FromHex("#fad398"), Color.FromHex("#cca031")),
            _ => (Color.DarkRed, Color.PaleVioletRed, Color.Crimson)
        };

        UpdateColor();
    }

    private void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        panel.BackgroundColor = Button.IsHovered ? _hoveredColor : _color;

        panel.BorderColor = _borderColor;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Button.OnPressed -= Selected;
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        SelectAction?.Invoke(Prototype, _availability);
    }

    public void SetScale(float scale)
    {
        NodeContainer.SetSize = new Vector2(80 * scale, 80 * scale);

        DisciplineBadge.SetSize = new Vector2(20, 20);
        SetPosition(DisciplineBadge, new Vector2(4, 4));
        DisciplineDisplay.SetSize = new Vector2(16, 16);
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
